name: PRECOMMIT-TIER-TESTS
on:
  pull_request:
    types: [labeled]

jobs:
  TRIGGER-SMOKE-TESTS:
    if: contains(toJson(github.event.pull_request.labels), 'ci-build-pass') && 
      (github.event.label.name == 'trigger-precommit-tier-tests') &&
      contains(toJson(github.event.pull_request.labels), 'smoketest-pass')
    concurrency:
    uses: Kitchen/RE-github-workflows/.github/workflows/ci-precommit-tier-tests.yaml@main